/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type SpeakerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "speaker";
};

export type DayReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "day";
};

export type Talk = {
  _id: string;
  _type: "talk";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  speaker?: SpeakerReference;
  day?: DayReference;
  track?: "frontend" | "performance" | "accessibility" | "tooling";
  startTime?: string;
  endTime?: string;
  location?: string;
  isKeynote?: boolean;
};

export type Day = {
  _id: string;
  _type: "day";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  date?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Speaker = {
  _id: string;
  _type: "speaker";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  jobTitle?: string;
  company?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eventName?: string;
  tagline?: string;
  eventDates?: string;
  venue?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SpeakerReference
  | DayReference
  | Talk
  | Day
  | SanityImageAssetReference
  | Speaker
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{ eventName, tagline, eventDates, venue }
export type SITE_SETTINGS_QUERY_RESULT = {
  eventName: string | null;
  tagline: string | null;
  eventDates: string | null;
  venue: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: HOME_QUERY
// Query: {  "settings": *[_type == "siteSettings"][0]{ tagline, eventDates, venue },  "talks": *[_type == "talk" && defined(speaker) && defined(day)]    | order(day->date asc, startTime asc, title asc) {      _id,      title,      description,      track,      isKeynote,      startTime,      endTime,      location,      "day": day->{ label, date },      "speaker": speaker->{ name, "slug": slug.current, jobTitle, company, bio, photo }    }}
export type HOME_QUERY_RESULT = {
  settings: {
    tagline: string | null;
    eventDates: string | null;
    venue: string | null;
  } | null;
  talks: Array<{
    _id: string;
    title: string | null;
    description: string | null;
    track: "accessibility" | "frontend" | "performance" | "tooling" | null;
    isKeynote: boolean | null;
    startTime: string | null;
    endTime: string | null;
    location: string | null;
    day: {
      label: string | null;
      date: string | null;
    };
    speaker: {
      name: string | null;
      slug: string | null;
      jobTitle: string | null;
      company: string | null;
      bio: string | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    };
  }>;
};

// Source: src/sanity/queries.ts
// Variable: SCHEDULE_QUERY
// Query: {  "days": *[_type == "day" && defined(date)] | order(date asc).date,  "talks": *[_type == "talk" && defined(speaker) && defined(day)]    | order(day->date asc, startTime asc, title asc) {      _id,      title,      description,      track,      isKeynote,      startTime,      endTime,      location,      "day": day->{ label, date },      "speaker": speaker->{ name, company }    }}
export type SCHEDULE_QUERY_RESULT = {
  days: Array<string>;
  talks: Array<{
    _id: string;
    title: string | null;
    description: string | null;
    track: "accessibility" | "frontend" | "performance" | "tooling" | null;
    isKeynote: boolean | null;
    startTime: string | null;
    endTime: string | null;
    location: string | null;
    day: {
      label: string | null;
      date: string | null;
    };
    speaker: {
      name: string | null;
      company: string | null;
    };
  }>;
};

// Source: src/sanity/queries.ts
// Variable: DESIGN_SYSTEM_SAMPLES_QUERY
// Query: {  "settings": *[_type == "siteSettings"][0]{ tagline, eventDates, venue },  "keynote": *[_type == "talk" && isKeynote][0]{    title,    startTime,    location,    "date": day->date,    "speaker": speaker->{ name, jobTitle, company, photo }  },  "speakers": *[_type == "speaker" && slug.current in ["elena-vasquez", "james-okonkwo", "priya-sharma", "ryan-osullivan"]]    | order(name asc) {      name,      "slug": slug.current,      jobTitle,      company,      bio,      photo,      "talks": *[_type == "talk" && references(^._id)] | order(day->date asc, startTime asc, title asc){        _id,        title,        track,        isKeynote,        startTime,        endTime,        "date": day->date      }    },  "talks": *[_type == "talk"] | order(day->date asc, startTime asc)[0...3]{    _id,    title,    description,    track,    isKeynote,    startTime,    endTime,    location,    "speaker": speaker->{ name, company },    "day": day->{ label, date }  }}
export type DESIGN_SYSTEM_SAMPLES_QUERY_RESULT = {
  settings: {
    tagline: string | null;
    eventDates: string | null;
    venue: string | null;
  } | null;
  keynote: {
    title: string | null;
    startTime: string | null;
    location: string | null;
    date: string | null;
    speaker: {
      name: string | null;
      jobTitle: string | null;
      company: string | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    } | null;
  } | null;
  speakers: Array<{
    name: string | null;
    slug: string | null;
    jobTitle: string | null;
    company: string | null;
    bio: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    talks: Array<{
      _id: string;
      title: string | null;
      track: "accessibility" | "frontend" | "performance" | "tooling" | null;
      isKeynote: boolean | null;
      startTime: string | null;
      endTime: string | null;
      date: string | null;
    }>;
  }>;
  talks: Array<{
    _id: string;
    title: string | null;
    description: string | null;
    track: "accessibility" | "frontend" | "performance" | "tooling" | null;
    isKeynote: boolean | null;
    startTime: string | null;
    endTime: string | null;
    location: string | null;
    speaker: {
      name: string | null;
      company: string | null;
    } | null;
    day: {
      label: string | null;
      date: string | null;
    } | null;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{ eventName, tagline, eventDates, venue }': SITE_SETTINGS_QUERY_RESULT;
    '{\n  "settings": *[_type == "siteSettings"][0]{ tagline, eventDates, venue },\n  "talks": *[_type == "talk" && defined(speaker) && defined(day)]\n    | order(day->date asc, startTime asc, title asc) {\n      _id,\n      title,\n      description,\n      track,\n      isKeynote,\n      startTime,\n      endTime,\n      location,\n      "day": day->{ label, date },\n      "speaker": speaker->{ name, "slug": slug.current, jobTitle, company, bio, photo }\n    }\n}': HOME_QUERY_RESULT;
    '{\n  "days": *[_type == "day" && defined(date)] | order(date asc).date,\n  "talks": *[_type == "talk" && defined(speaker) && defined(day)]\n    | order(day->date asc, startTime asc, title asc) {\n      _id,\n      title,\n      description,\n      track,\n      isKeynote,\n      startTime,\n      endTime,\n      location,\n      "day": day->{ label, date },\n      "speaker": speaker->{ name, company }\n    }\n}': SCHEDULE_QUERY_RESULT;
    '{\n  "settings": *[_type == "siteSettings"][0]{ tagline, eventDates, venue },\n  "keynote": *[_type == "talk" && isKeynote][0]{\n    title,\n    startTime,\n    location,\n    "date": day->date,\n    "speaker": speaker->{ name, jobTitle, company, photo }\n  },\n  "speakers": *[_type == "speaker" && slug.current in ["elena-vasquez", "james-okonkwo", "priya-sharma", "ryan-osullivan"]]\n    | order(name asc) {\n      name,\n      "slug": slug.current,\n      jobTitle,\n      company,\n      bio,\n      photo,\n      "talks": *[_type == "talk" && references(^._id)] | order(day->date asc, startTime asc, title asc){\n        _id,\n        title,\n        track,\n        isKeynote,\n        startTime,\n        endTime,\n        "date": day->date\n      }\n    },\n  "talks": *[_type == "talk"] | order(day->date asc, startTime asc)[0...3]{\n    _id,\n    title,\n    description,\n    track,\n    isKeynote,\n    startTime,\n    endTime,\n    location,\n    "speaker": speaker->{ name, company },\n    "day": day->{ label, date }\n  }\n}': DESIGN_SYSTEM_SAMPLES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
